-- First, remove the table if it exists
drop table if exists bookmarks;

-- Create the table anew
CREATE TABLE bookmarks (
  id INTEGER primary key generated by default as identity,
  title TEXT NOT NULL,
  url VARCHAR(2083),
  rating INTEGER NOT NULL,
  descpition TEXT,
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks (title, rating)
values
  ('Title1', '2'),
  ('Title2', '3'),
  ('Title3', '4');